---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    attributes:
      postgresql:
        enable_pgdg_apt: true
  - name: ubuntu-12.04
    attributes:
      postgresql:
        enable_pgdg_apt: true
  - name: centos-6.6
    attributes:
      postgresql:
        enable_pgdg_yum: true

suites:
  - name: default
    runlist:
      - recipe[pg-multi::default]
    attributes:
      postgresql:
        version: '9.3'  

  - name: mu14
    driver:
      vm_hostname: master-ubuntu-14
      network:
      - ["private_network", {ip: "192.168.0.21"}]
    run_list:
    - recipe[pg-multi::pg_master]
    excludes: ['ubuntu-12.04', 'centos-6.6']
    attributes:
      postgresql:
        version: '9.3'
      pg-multi:
        master_ip: '192.168.0.21'
        slave_ip: ['192.168.0.22']

  - name: su14
    driver:
      vm_hostname: slave-ubuntu-14
      network:
      - ["private_network", {ip: "192.168.0.22"}]
    run_list:
    - recipe[pg-multi::pg_slave]
    excludes: ['ubuntu-12.04', 'centos-6.6']
    attributes:
      postgresql:
        version: '9.3'
      pg-multi:
        master_ip: '192.168.0.21'
        slave_ip: ['192.168.0.22']

  - name: mu12
    driver:
      vm_hostname: master-ubuntu-12
      network:
      - ["private_network", {ip: "192.168.0.23"}]
    run_list:
    - recipe[pg-multi::pg_master]
    excludes: ['ubuntu-14.04', 'centos-6.6']
    attributes:
      postgresql:
        version: '9.3'
      pg-multi:
        master_ip: '192.168.0.23'
        slave_ip: ['192.168.0.24']

  - name: su12
    driver:
      vm_hostname: slave-ubuntu-12
      network:
      - ["private_network", {ip: "192.168.0.24"}]
    run_list:
    - recipe[pg-multi::pg_slave]
    excludes: ['ubuntu-14.04', 'centos-6.6']
    attributes:
      postgresql:
        version: '9.3'
      pg-multi:
        master_ip: '192.168.0.23'
        slave_ip: ['192.168.0.24']

  - name: mc6
    driver:
      vm_hostname: master-centos-6
      network:
      - ["private_network", {ip: "192.168.0.25"}]
    run_list:
    - recipe[pg-multi::pg_master]
    excludes: ['ubuntu-14.04', 'ubuntu-12.04']
    attributes:
      postgresql:
        version: '9.3'
      pg-multi:
        master_ip: '192.168.0.25'
        slave_ip: ['192.168.0.26']

  - name: sc6
    driver:
      vm_hostname: slave-centos-6
      network:
      - ["private_network", {ip: "192.168.0.26"}]
    run_list:
    - recipe[pg-multi::pg_slave]
    excludes: ['ubuntu-14.04', 'ubuntu-12.04']
    attributes:
      postgresql:
        version: '9.3'
      pg-multi:
        master_ip: '192.168.0.25'
        slave_ip: ['192.168.0.26']
