---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    attributes:
      postgresql:
        enable_pgdg_apt: true
  - name: ubuntu-12.04
    attributes:
      postgresql:
        enable_pgdg_apt: true
  - name: centos-6.6
    attributes:
      postgresql:
        enable_pgdg_yum: true

suites:
  - name: default
    runlist:
      - recipe[pg-multi::default]
    attributes:
      postgresql:
        version: '9.3'
